{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "contex.fullname" . }}
  labels:
    {{- include "contex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "contex.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /api/metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
