apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- servicemonitor.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: contex
  app.kubernetes.io/part-of: contex

namespace: contex
