apiVersion: v1
kind: Service
metadata:
  name: contex
  labels:
    app: contex
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: contex
